### PR TITLE
Fix false positive in *_vpc_public_subnet.py

### PR DESCRIPTION
**Pull request by msambol**
Need a second eye here but I believe the current
code produces a false positive. For example, what
if the main route table has a public route but the subnet 
is associated with a private route table?

### CODE REVIEW

**Comment by msambol** [comment]
@droidlabour Wouldn't mind your review here since you authored the original. Thanks!

**Comment by msambol** [comment]
@aaronkhoo Can you review and merge? One of my colleagues confirmed this bug too.

**Comment by BetaKevin** [comment]
I don't think this will capture a certain use case.  Specifically with RDS instances as it needs multiple subnets to fail.

If the RDS instance has more than 1 subnetidentifier and the following is true:
- 1 or more subnets are private and not using the main table
- 1 subnet is public using the main table.  

In this case the code you have submitted will pass even though it should fail.

**Comment by msambol** [comment]
@BetaKevin Fixed. Thanks!

**Comment by msambol** [comment]
@aaronkhoo can you review? This fixes a bug with 2 rules.

**Comment by jwasham** [comment]
Thanks for the fix, @msambol !

**Pull request merged**
